apiVersion: apps.onex.io/v1alpha1
kind: MinerSet
metadata:
  labels:
    app.kubernetes.io/name: onex-miner-operator
    app.kubernetes.io/managed-by: kustomize
  name: minerset-sample
spec:
  # TODO(user): Add fields here
